export enum OrderStatus {
    FUND_NOT_AUTHORIZED = 'FUND_NOT_AUTHORIZED',
    PENDING = 'PENDING',
    CONFIRMED = 'CONFIRMED',
    EXPIRED = 'EXPIRED',
    CANCELLED = 'CANCELLED',
    COMPLETED = 'COMPLETED'
}
