workflows:
  version: 2.1
  deploy-to-heroku:
    jobs:
      - build
      - heroku/deploy-via-git:
          environment:
            TEST_ENV_VAR: "something something something"
          requires:
            - build

version: 2.1
orbs:
  heroku: circleci/heroku@0.0.8

jobs:
  build:
    working_directory: ~/enso-street-web-server
    docker:
      - image: circleci/node:12-browsers
      - image: circleci/postgres:latest-ram
        environment:
          POSTGRES_USER: enso-street
          POSTGRES_DB: enso-street-test
      - image: circleci/redis:latest

    steps:
      - checkout

      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'

      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}

      - run: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

      - run:
          name: test
          command: npm test