workflows:
  version: 2.1
  deploy-to-heroku:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build

version: 2.1
orbs:
  heroku: circleci/heroku@1.0.0

jobs:
  build:
    working_directory: ~/enso-street-web-server
    docker:
      - image: circleci/node:12-browsers
      - image: circleci/postgres:latest-ram
        environment:
          POSTGRES_USER: enso-street
      - image: circleci/redis:latest

    steps:
      - checkout

      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'

      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}

      - run: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

      - run:
          name: test
          command: ./node_modules/db-migrate/bin/db-migrate up -e test && npm test
          environment:
            databaseUri: postgres://enso-street@localhost:5432/circle_test
            sessionSecret: this-is-a-session-secret