version: 2.1
jobs:
  build:
    working_directory: ~/enso-street-web-server
    docker:
      - image: circleci/node:12-browsers
      - image: circleci/postgres:latest-ram

    steps:
      - checkout

      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'

      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}

      - run: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

      - run:
          name: test
          command: db-migrate up && npm test
          environment:
            databaseUri: postgres://postgres@localhost:5432/circle_test

      - run:
          name: Setup CF CLI
          command: |
            curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
            sudo dpkg -i cf-cli_amd64.deb
            cf -v
            cf api https://api.run.pivotal.io
            cf auth "$CF_USER" "$CF_PASSWORD"
            cf target -o hanchenjhc -s development

      - run:
          name: CF Deploy
          command: |
            cf push